### ISSUE TITLE
[Question] `recent-menu.lua` and `SimpleHistory.lua` and feature request

### ISSUE THREAD

**Issue by BhaturaGuy** [natural-harmonia-gropius/recent-menu#1]
Can it somehow read the history file created by `SimpleHistory.lua`?
Also if there's an option to change display name from `media-title` to `filename` in `recent_menu.conf`

**Comment by natural-harmonia-gropius** [comment]
> Can it somehow read the history file created by `SimpleHistory.lua`? 

Maybe in future, But SimpleHistory is a 2000+ line giant scripts.

> Also if there's an option to change display name from `media-title` to `filename` in `recent_menu.conf`

Will do.

**Comment by dyphire** [comment]
I added similar uosc integration for another history script of [recent.lua](https://github.com/dyphire/recent/blob/dev/recent.lua).

SimpleHistory.lua is extremely rich in functions. Adding similar integration may lose many functions.

**Comment by natural-harmonia-gropius** [comment]
It shows both of filename and title now.
![image](https://user-images.githubusercontent.com/50797982/218689436-51e5f09c-0353-4eb4-aa9c-3285ef3e745d.png)

**Comment by natural-harmonia-gropius** [comment]
https://github.com/natural-harmonia-gropius/recent-menu/commit/5e42bdbe432cc82a37696381c3078a3c22f77bfb

**Comment by dyphire** [comment]
> [5e42bdb](https://github.com/natural-harmonia-gropius/recent-menu/commit/5e42bdbe432cc82a37696381c3078a3c22f77bfb)

It can be optimized to display only the file name when the file name and title are the same

**Comment by natural-harmonia-gropius** [comment]
> It can be optimized to display only the file name when the file name and title are the same

https://github.com/natural-harmonia-gropius/recent-menu/commit/c6a201ba47d4c039e15895bd085beca6484e64b3
