### ISSUE TITLE
 Lua error: .../apps/mpv/current/portable_config/scripts/recentmenu.lua:131: bad argument #1 to 'ipairs' (table expected, got nil)

### ISSUE THREAD

**Issue by SonaliBendre** [natural-harmonia-gropius/recent-menu#13]
[recentmenu]
[recentmenu] stack traceback:
[recentmenu]    .../apps/mpv/current/portable_config/scripts/recentmenu.lua:131: in function 'append_item'
[recentmenu]    .../apps/mpv/current/portable_config/scripts/recentmenu.lua:190: in function 'handler'
[recentmenu]    mp.defaults:510: in function 'call_event_handlers'
[recentmenu]    mp.defaults:552: in function 'dispatch_events'
[recentmenu]    mp.defaults:503: in function <mp.defaults:502>
[recentmenu]    [C]: at 0x7ff721b0de20
[recentmenu]    [C]: at 0x7ff721b0e310
[recentmenu] Lua error: .../apps/mpv/current/portable_config/scripts/recentmenu.lua:131: bad argument #1 to 'ipairs' (table expected, got nil)

**Comment by natural-harmonia-gropius** [comment]
Are you using scripts from this repo?
![image](https://github.com/natural-harmonia-gropius/recent-menu/assets/50797982/476692cf-cd5b-4026-9c45-a44d7bae6fbd)
![image](https://github.com/natural-harmonia-gropius/recent-menu/assets/50797982/006716bb-0907-46c4-815a-895de845994e)

**Comment by SonaliBendre** [comment]
what does it supposed to mean?

**Comment by natural-harmonia-gropius** [comment]
Download script from https://raw.githubusercontent.com/natural-harmonia-gropius/recent-menu/master/recentmenu.lua, replace one you are using and try again.

**Comment by po5** [comment]
Looks like he's on commit 37e4054872ee201c71ada77af50b71c7a8a53bf5.  
What likely happened is that the `recent.json` write failed somehow (disk full?), leading to a 0-byte file that makes `utils.parse_json()` return nil.  
Confirmed to still be an issue on the latest commit by manually emptying `recent.json`.

```
[recentmenu] 
[recentmenu] stack traceback:
[recentmenu]    [C]: in function 'ipairs'
[recentmenu]    /home/eva/.config/mpv/scripts/recentmenu.lua:121: in function 'remove_deleted'
[recentmenu]    /home/eva/.config/mpv/scripts/recentmenu.lua:160: in function 'read_json'
[recentmenu]    /home/eva/.config/mpv/scripts/recentmenu.lua:183: in function 'append_item'
[recentmenu]    /home/eva/.config/mpv/scripts/recentmenu.lua:224: in function 'handler'
[recentmenu]    mp.defaults:510: in function 'call_event_handlers'
[recentmenu]    mp.defaults:552: in function 'dispatch_events'
[recentmenu]    mp.defaults:503: in function <mp.defaults:502>
[recentmenu]    [C]: in ?
[recentmenu]    [C]: in ?
[recentmenu] Lua error: /home/eva/.config/mpv/scripts/recentmenu.lua:121: bad argument #1 to 'ipairs' (table expected, got nil)
```

`utils.parse_json(json)` -> `utils.parse_json(json) or {}` is enough to fix it.

**Comment by natural-harmonia-gropius** [comment]
You can download latest version to fix this.

closed by https://github.com/natural-harmonia-gropius/recent-menu/commit/3646bc5476aed671250ff361a1588dd987b9e9e9.

> What likely happened is that the recent.json write failed somehow (disk full?)

I didn't expect this to happen. Thanks!

**Comment by po5** [comment]
> But this only fixes the crash, I think the script would not work as expected

Works fine here, history gets saved and can be displayed.

**Comment by natural-harmonia-gropius** [comment]
I guess he will encounter another error in `write_json`, waiting for his feedback.
