### ISSUE TITLE
Autosave compatibility?

### ISSUE THREAD

**Issue by Xeiv** [natural-harmonia-gropius/recent-menu#15]
Hello, is it possible to make it work together with the autosave script ↓ or add autosave in this script?  
https://gist.github.com/CyberShadow/2f71a97fb85ed42146f6d9f522bc34ef

When I manually open it again it will resume at a point but when I open it using recent files it resumes at a completely different point. 
Basically, it resumes at a different time depending on how I open it. 

If not then it's fine, I was just wondering why it's inconsistent 👀 I'm new to Lua/mpv but have been enjoying using mpv along with your script 😄

**Comment by natural-harmonia-gropius** [comment]
From https://github.com/natural-harmonia-gropius/recent-menu/commit/706f4e525561b2436a9d8f57ac51b7bcddd5b428 this script always use `/` in path, but when you open it with explorer, it uses `\`. mpv treat "a/b/c" and "a\b\c" are different paths.

**Comment by Xeiv** [comment]
Ah I understand now, thank you

**Comment by natural-harmonia-gropius** [comment]
Since https://github.com/natural-harmonia-gropius/recent-menu/commit/08de6cc1e131e69ea3f60b9a52244bea251b25d3 revert the slash changes and mpv develpoers doesn't interested in serializing the path, nothing more could be done by me, so I close this issue.
