### ISSUE TITLE
Question on maximum number of entries 

### ISSUE THREAD

**Issue by Zabooby** [natural-harmonia-gropius/recent-menu#2]
Is there a maximum number of entries right now, would you be interested in maybe adding an option in recent-menu.conf to let us choose how many entries to list?

**Comment by natural-harmonia-gropius** [comment]
https://github.com/natural-harmonia-gropius/recent-menu/commit/b100f188eabb33e01eec20f4665250e1e69d9d67

**Comment by Zabooby** [comment]
Now do I just make recent-menu.conf in the script-opts folder and add `recent_menu-length=20`?

**Comment by natural-harmonia-gropius** [comment]
`length=20` I guess. Haven't used script-opts.

**Comment by Zabooby** [comment]
Tried `length=4 ` and it's not working.

**Comment by natural-harmonia-gropius** [comment]
`recent_menu.conf` This will work, but I'm going to remove the line

**Comment by natural-harmonia-gropius** [comment]
`script-opts/recentmenu.conf`
`length=4`
should works

**Comment by Zabooby** [comment]
Ok it's working now just had to delete the old recent.json. 

Is there a way I can move the recent.json to script-opts or does it have to be here:
![image](https://user-images.githubusercontent.com/78969986/218685978-ff4255ff-87ce-49de-b6c1-374f94d3d1ce.png)

**Comment by natural-harmonia-gropius** [comment]
Change the path here, I'll add an option later.
![image](https://user-images.githubusercontent.com/50797982/218686397-f111b45a-6bea-49b8-a001-067b63aee69a.png)

**Comment by natural-harmonia-gropius** [comment]
path=~~/script-opts/recent.json

**Comment by Zabooby** [comment]
Yup it works, thanks for making this script, I actually made a feature request for this exact feature a while ago tomasklaen/uosc/issues/404.
