### ISSUE TITLE
Please support direct integration with MPV osc.

### ISSUE THREAD

**Issue by zhouxinghong** [natural-harmonia-gropius/recent-menu#26]
Should support use when the native default UI is not uosc

Since uosc has a serious performance impact in some cases, it would be nice to support its use in the default UI as well.

Windows 10

**Comment by natural-harmonia-gropius** [comment]
[dyn_menu.lua](https://github.com/tsl0922/mpv-menu-plugin/blob/main/src/lua/dyn_menu.lua) + following input.conf works for me.

```
MBTN_RIGHT          context-menu
_                   script-binding recentmenu/open                              #menu: Recently Played #@recent
```

**Comment by zhouxinghong** [comment]
Please support direct integration with MPV osc.

**Comment by natural-harmonia-gropius** [comment]
No "direct", recent.lua + [dyn_menu.lua](https://github.com/tsl0922/mpv-menu-plugin/blob/main/src/lua/dyn_menu.lua) + input.conf = "integration".

**Comment by zhouxinghong** [comment]
`No "direct", recent.lua + [dyn_menu.lua](https://github.com/tsl0922/mpv-menu-plugin/blob/main/src/lua/dyn_menu.lua) + input.conf = "integration".`
How is it configured?

**Comment by natural-harmonia-gropius** [comment]
https://github.com/natural-harmonia-gropius/recent-menu/issues/26#issuecomment-2085068184
https://github.com/natural-harmonia-gropius/recent-menu/issues/26#issuecomment-2085068184

**Comment by zhouxinghong** [comment]
Thank you!
