### ISSUE TITLE
Feature: Add character restrictions to menu items to strip long filename or title

### ISSUE THREAD

**Issue by dyphire** [natural-harmonia-gropius/recent-menu#3]
![image](https://user-images.githubusercontent.com/61936050/218698077-3d213ce2-04b6-4726-8375-2177d9e54934.png)

**Comment by natural-harmonia-gropius** [comment]
https://github.com/natural-harmonia-gropius/recent-menu/commit/f8abf29004e95f87816379260fcaa15961808506

![image](https://user-images.githubusercontent.com/50797982/218713410-30db7892-37c3-4b1c-a734-002c092ad6b2.png)
![image](https://user-images.githubusercontent.com/50797982/218718803-15dc2a0f-dc32-44f6-8b1c-f78e9ac2a43a.png)

**Comment by natural-harmonia-gropius** [comment]
![image](https://user-images.githubusercontent.com/50797982/218722992-2a39558c-0b1b-41f1-a8d1-06be186939f4.png)

**Comment by natural-harmonia-gropius** [comment]
https://github.com/natural-harmonia-gropius/recent-menu/commit/e8c178333d8f4ab2f9e30139747a318fc1dd3664
