### ISSUE TITLE
Too much JSON file IO

### ISSUE THREAD

**Issue by stax76** [natural-harmonia-gropius/recent-menu#33]
The script reads/writes a lot of JSON data on every file change, could this be changed to read JSON only on startup and write JSON only on shutdown? Make it maybe optional?

**Comment by natural-harmonia-gropius** [comment]
https://github.com/natural-harmonia-gropius/recent-menu/pull/34

---

The ideal implementation is

```
Instance1 -> SharedWorker -> Database
Instance2 -> SharedWorker -> Database
```

`read_json` and `write_json` should be replaced with `getState()` and `setState()`, data stay in memory.
SharedWorker start with the first instance and end with the last instance, load and storage data in startup and quit.

**Comment by stax76** [comment]
Thanks for the quick response. There is a typo here:

`mp.register_event("shutdown ",`

**Comment by natural-harmonia-gropius** [comment]
https://github.com/natural-harmonia-gropius/recent-menu/pull/34 been merged. this option default to false, so you need to enable it in conf.
