### ISSUE TITLE
command_palette.lua integration

### ISSUE THREAD

**Issue by stax76** [natural-harmonia-gropius/recent-menu#35]
I added API support to my command palette script, which you can find here:

https://github.com/stax76/mpv-scripts

Integration with your recent-menu script would be great.

The API is uosc compatible, there isn't full uosc API support, it's limited to what your script uses.

It can be called like so:

```Lua
local json = utils.format_json(menu)
mp.commandv('script-message-to',
            'command_palette',
            'show-command-palette-json', json)
```

I suggest that all integrations can be invoked with a command.

```
script-message-to recentmenu show-recent-menu select
script-message-to recentmenu show-recent-menu uosc
script-message-to recentmenu show-recent-menu command-palette
```

**Comment by natural-harmonia-gropius** [comment]
Thank you. here you are: https://github.com/natural-harmonia-gropius/recent-menu/pull/36

A request, I need command_palette to broadcast 'command-palette-version' so that fallbacks in `open_menu()` can work.

**Comment by stax76** [comment]
Great, I added version support as message and user-data and documented everything in the readme file, it's already committed to the main branch because I'm not very good at using git.

Everything worked in my tests.

https://github.com/stax76/mpv-scripts/commit/59661dba963a80078e44a9077e9f3fc0ef12d872

https://github.com/stax76/mpv-scripts/commit/1bcd1b6f2ebeb285ca9647945c542781557ba9e7

**Comment by natural-harmonia-gropius** [comment]
https://github.com/natural-harmonia-gropius/recent-menu/commit/6e8d52b07b1f1d059b56c76dc1c3dc01693c2d75
