### ISSUE TITLE
菜单宽度控制有点问题

### ISSUE THREAD

**Issue by verygoodlee** [natural-harmonia-gropius/recent-menu#38]
在非uosc菜单里可能会出现这种宽度差距过大的情况
1.  yt-dlp解析的网络视频，标题：`一口气了解FLUX.1：AI生图的“新王”，凭什么震惊世界？FLUX模型使用教程，基本用法到进阶应用，一网打尽！（含SD Forge与ComfyUI整合包）`
2. 本地视频，文件名：`[BeanSub&FZSD&VCB-Studio] Gekijouban Kimetsu no Yaiba Mugen Ressha Hen [Ma10p_1080p].mkv`
![image](https://github.com/user-attachments/assets/a3eb204a-0d68-4ff5-9a97-a161678fdabb)

最开始主要是为uosc设计的，hint信息占用了一部分宽度，
但是在原生上下文菜单和input.select菜单中没用上这部分hint信息，导致有hint和无hint两种情况下宽度差距太大。
```json
[
    {
        "title": "一口气了解FLUX.1：AI生图的“新王”，凭什么震惊世界",
        "value": [
            "loadfile",
            "https://www.bilibili.com/video/BV1UytNexEUk/?vd_source=a605e8e4eb3b5e446d9dd40d695d02b7"
        ],
        "hint": "?vd_source=a605e8e4eb3b5e446d"
    },
    {
        "title": "[BeanSub&FZSD&VCB-Studio] Gekijouban Kimetsu no Yaiba Mugen Ressha Hen [Ma10p_10",
        "value": [
            "loadfile",
            "D:\\Videos\\[BeanSub&FZSD&VCB-Studio] Gekijouban Kimetsu no Yaiba Mugen Ressha Hen [Ma10p_1080p][x265_flac].mkv"
        ],
        "hint": ""
    }
]
```

推荐在存储时不做截取操作，这样不好适配不同类型的菜单，

直接存原始的标题和文件名，打开菜单时再根据当前的菜单类型去使用不同的截取策略。

**Comment by natural-harmonia-gropius** [comment]
得大改，我有空弄

**Comment by natural-harmonia-gropius** [comment]
我把width直接删了，菜单会不会太长？

**Comment by verygoodlee** [comment]
可能有部分超长文件名影响体验，虽然遇到到的概率不高，
宽度限制确实也很难做的准，特别是非等宽字体，CJK字符看做2宽度也只是个估计。

新版的 后缀/协议 + 时间 的提示信息挺不错的，建议把 后缀/协议 转成大写，看起来应该更协调

**Comment by natural-harmonia-gropius** [comment]
> 转成大写

改了
