### ISSUE TITLE
Feature: Use `update-menu` to  switch different types of submenus

### ISSUE THREAD

**Issue by dyphire** [natural-harmonia-gropius/recent-menu#4]
Suggested type of submenu: resemble `distinct` and `protocols` at [SimpleHistory.lua](https://github.com/Eisa01/mpv-scripts/blob/master/scripts/SimpleHistory.lua), other types seem unnecessary.

**Comment by natural-harmonia-gropius** [comment]
> "distinct" to show recent saved entries for files in different paths.

我不太理解，有图吗？

**Comment by dyphire** [comment]
> > "distinct" to show recent saved entries for files in different paths.
> 
> 我不太理解，有图吗？

其实就是同一目录下的播放记录在`distinct`类型中只显示最后一个，实现只显示不同目录的播放历史（同时排除网络播放）。我个人觉得这种历史显示方式很有用，`distinct`是我使用SimpleHistory.lua时的默认显示方式（键位）

**Comment by natural-harmonia-gropius** [comment]
> distinct

将同一目录下当前文件名和记录里的文件名消除字符串首尾的相同字符后留下的都是数字的两个文件视为同一系列过滤掉可以吗？

> protocols

这个有去掉的理由吗？
我能想到的问题就是长得丑，如果这样我会做主副文本换位

> 历史条目保存数量和显示条目数量保持一致

我不想存用户无法直观知道仍被存储的数据，更不想用lua玩数据结构

**Comment by dyphire** [comment]
> > distinct
> 
> 将同一目录下当前文件名和记录里的文件名消除字符串首尾的相同字符后留下的都是数字的两个文件视为同一系列过滤掉可以吗？

这种方法并不能很好地处理同目录的播放记录，因为无法预测目录下的文件名结构，举两个例子：
![image](https://user-images.githubusercontent.com/61936050/218759716-6e0d487a-0ef3-4d9c-9118-38d56667968c.png)
![image](https://user-images.githubusercontent.com/61936050/218759746-10f0fb54-019c-4096-8f67-9870eba84d31.png)

> > protocols
> 
> 这个有去掉的理由吗？ 我能想到的问题就是长得丑，如果这样我会做主副文本换位

去掉原因是我提到了`distinct`和`protocols`两种单独的分类菜单，protocols 应该列入单独的菜单。不过如果不考虑实现这种分类菜单的话，对 protocols 进行主副文本换位是个不错的改变

> > 历史条目保存数量和显示条目数量保持一致
> 
> 我不想存用户无法直观知道仍被存储的数据，更不想用lua玩数据结构

如果要实现我提出的分类菜单的功能就需要改变这一点，不然条目不足就不够实用
如果不准备实现的话后续我可以考虑在fork版上自行尝试实现

**Comment by natural-harmonia-gropius** [comment]
1. https://github.com/natural-harmonia-gropius/recent-menu/commit/51d25183066f4d6afe56478e09aefc39296ec9cf 同一目录下重复率 50% 以上的会被忽略
2. https://github.com/natural-harmonia-gropius/recent-menu/commit/782d93c6ea3bcfc43847dace845ef52d7f9e650a 在有标题的时候交换，前缀也可能是 bd:// dvd:// 这样的本地文件
3. 你实现了之后我觉得可以就合并

**Comment by natural-harmonia-gropius** [comment]
我刚刚修了个string:find不知道为什么会返回nil的问题，可能报错了，现在再试试？
没理由新的加不进去的，新的无论如何都会被加进去

**Comment by dyphire** [comment]
> 我刚刚修了个string:find不知道为什么会返回nil的问题，可能报错了，现在再试试？ 没理由新的加不进去的，新的无论如何都会被加进去，我这边正常

删除旧json后可以正常记录了，但功能似乎没有生效
![image](https://user-images.githubusercontent.com/61936050/218788982-8e9bdd84-9491-4421-9911-a9dc1c5a97cd.png)

**Comment by natural-harmonia-gropius** [comment]
复制完整路径我看看
![image](https://user-images.githubusercontent.com/50797982/218789425-c1fffe9c-55a4-427e-b637-c63e21b41185.png)

**Comment by dyphire** [comment]
F:\Download\境界触发者  第二季\[MMSUB] World Trigger 2nd Season - 01 [WebRip 1080p HEVC-10bit AAC ASS×2].mkv

G:\Anime\[HQR] Tetsuwan Birdy Decode 02 TV [DVDRip 1272x720 HEVC Flac]\[HQR] Tetsuwan Birdy Decode 02 TV -01- (DVDRip 1272x720 HEVC Flac).mkv

对我来说任何路径都一样，应该不是这个问题

**Comment by natural-harmonia-gropius** [comment]
现在应该真的好了

**Comment by dyphire** [comment]
> 现在应该真的好了

最新版本确实可以了，但是对于上面第一个图例里的系列文件效果不是很好
![image](https://user-images.githubusercontent.com/61936050/218792041-3332d39f-1762-4e2d-b318-c0a6a5b6baf5.png)
整体相似度不足50%，或许可以考虑再匹配下开头多少字符相同下的逻辑

**Comment by dyphire** [comment]
> 整体相似度不足50%，或许可以考虑再匹配下在数字前的字符相同下的逻辑（感觉误杀率会比相似度高很多）

以下补丁可用:
```diff
---
 recentmenu.lua | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/recentmenu.lua b/recentmenu.lua
index a16bdeb..749cd53 100644
--- a/recentmenu.lua
+++ b/recentmenu.lua
@@ -103,6 +103,8 @@ function is_same_series(s1, s2)
     if limit > #temp then
         return true
     end
+    local sub1, sub2 = s1:match("(%.?)0*%d+"), s2:match("(%.?)0*%d+")
+    if sub1 == sub2 then return true end
     return false
 end
 
-- 
```

**Comment by natural-harmonia-gropius** [comment]
最好加上0前一个字符不是数字的判断，不然像什么709，2020也会被算进去

不管怎么样明天再说了

**Comment by natural-harmonia-gropius** [comment]
我发现之前比对的文件名是不完整的显示文件名，现在比较完整的，不知道你的测试用例有没有改善。

**Comment by dyphire** [comment]
> 我发现之前比对的文件名是不完整的显示文件名，现在比较完整的，不知道你的测试用例有没有改善。

没有改善，我一开始放的那个图例里的系列文件名不适用于相似度匹配
![image](https://user-images.githubusercontent.com/61936050/218759716-6e0d487a-0ef3-4d9c-9118-38d56667968c.png)
我上面那个补丁可以很好地处理这类文件

**Comment by natural-harmonia-gropius** [comment]
合并了，分类菜单看你的了
