### ISSUE TITLE
Feature: Ability to remember YouTube/Twitch recently played videos

### ISSUE THREAD

**Issue by Zabooby** [natural-harmonia-gropius/recent-menu#8]
I'm not sure if this is possible or how hard it would be to implement, but right now it can be annoying to constantly find and drag links into mpv of videos that I'm still watching. Implementing it into your script would remove this inconvenience.

**Comment by natural-harmonia-gropius** [comment]
It's already there. or you want pinned?

![image](https://user-images.githubusercontent.com/50797982/221783905-42a063c9-e53b-402d-a45b-80eafb6c7005.png)

**Comment by Zabooby** [comment]
I'm stupid, its working just how I want it to. It didn't appear at first so I thought it didn't work.

Would you be interested in opening a pr in the uosc repo so that this script can reach more users?

**Comment by natural-harmonia-gropius** [comment]
> Would you be interested in opening a pr in the uosc repo so that this script can reach more users?

Something like suggested extension is better.
