### ISSUE TITLE
missing youtube Playlist in recently played

### ISSUE THREAD

**Issue by candrapersada** [natural-harmonia-gropius/recent-menu#9]
when continuing to watch using recently played, Youtube Playlist is missing

**Comment by natural-harmonia-gropius** [comment]
Any errors in console?
![image](https://user-images.githubusercontent.com/50797982/224120895-7650c08d-9a38-4663-8983-0216d0c50088.png)

**Comment by candrapersada** [comment]
![gambar](https://user-images.githubusercontent.com/36833664/224124940-85b84eca-2b8d-4f41-a6ed-bcabfe93111f.png)
aftar use
![gambar](https://user-images.githubusercontent.com/36833664/224125307-ea81dc44-4e10-4c4e-8929-4783e0370115.png)
missing youtube playlist

**Comment by natural-harmonia-gropius** [comment]
Videos that are treated as the same series will only keep the most recent one. I would add an option to allow this behavior to be turned off.

**Comment by candrapersada** [comment]
and how to save recent in bookmarks?

**Comment by candrapersada** [comment]
that allows saving and loading named bookmarks and remembering the last watched video.

**Comment by natural-harmonia-gropius** [comment]
I mean, this behavior requires some kind of operation to do it. so what kind of operation do you want it to be?

A example.
![image](https://user-images.githubusercontent.com/50797982/224888038-a2df2f9b-afd4-4a32-b52f-c962383424c4.png)

**Comment by candrapersada** [comment]
> I mean, this behavior requires some kind of operation to do it. so what kind of operation do you want it to be?

the options are similar to those drawn but done as Recently played in mpv

**Comment by natural-harmonia-gropius** [comment]
As I said above, this is impossible for uosc.

**Comment by natural-harmonia-gropius** [comment]
If you are using a separate bookmarks, then I can't help you.
If you want to have pinned in the recent, I need viable solution.

**Comment by natural-harmonia-gropius** [comment]
After thinking, pined item will not be implemented.
